const SUPABASE_URL='https://owceeowarwqjsxpylnoo.supabase.co';
const SUPABASE_KEY='sb_publishable_DxH30XOgchm8PifrXNKn-w_9fRNFoQg';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'};
const libraryView=document.querySelector('#libraryView'),editorView=document.querySelector('#editorView'),notesGrid=document.querySelector('#notesGrid');
const editorTitle=document.querySelector('#editorTitle'),editorContent=document.querySelector('#editorContent'),saveStatus=document.querySelector('#saveStatus');
const dictionaryPopup=document.querySelector('#dictionaryPopup'),dictionaryWord=document.querySelector('#dictionaryWord'),dictionaryMeaning=document.querySelector('#dictionaryMeaning'),dictionarySource=document.querySelector('#dictionarySource');
let currentNote=null,saveTimer=null,saveChain=Promise.resolve();
function cleanHtml(html,compact=false){const template=document.createElement('template');template.innerHTML=html;const allowed=new Set(['B','STRONG','I','EM','U','BR','DIV','P']),blocks=new Set(['H1','H2','H3','H4','H5','H6','LI','TR','BLOCKQUOTE']);for(const element of[...template.content.querySelectorAll('*')].reverse()){if(element.tagName==='SCRIPT'||element.tagName==='STYLE'){element.remove();continue;}if(allowed.has(element.tagName)){for(const attribute of[...element.attributes])element.removeAttribute(attribute.name);continue;}const style=(element.getAttribute('style')||'').toLowerCase(),bold=/font-weight\s*:\s*(bold|[6-9]00)/.test(style),italic=/font-style\s*:\s*italic/.test(style),underline=/text-decoration(?:-line)?\s*:[^;]*underline/.test(style);let root=null,inside=null;for(const tag of[bold?'strong':'',italic?'em':'',underline?'u':''].filter(Boolean)){const wrapper=document.createElement(tag);if(inside)inside.append(wrapper);else root=wrapper;inside=wrapper;}const fragment=document.createDocumentFragment(),target=inside||fragment;while(element.firstChild)target.append(element.firstChild);if(root)fragment.append(root);if(blocks.has(element.tagName))fragment.append(document.createElement('br'));element.replaceWith(fragment);}if(compact){for(const block of[...template.content.querySelectorAll('p,div')].reverse())if(!block.textContent.replace(/\u00a0/g,'').trim())block.remove();for(const br of[...template.content.querySelectorAll('br')])if(!br.previousSibling||!br.nextSibling||br.previousSibling.nodeName==='BR')br.remove();for(const node of[...template.content.childNodes])if(node.nodeType===Node.TEXT_NODE&&!node.textContent.replace(/\u00a0/g,'').trim())node.remove();}return template.innerHTML.trim();}
async function rpc(name,body){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(body)});if(!response.ok)throw Error('The notes database needs the latest Post it Supabase setup.');return response.json();}
function dateLabel(value){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
async function loadNotes(){notesGrid.innerHTML='<div class="empty">READING CLOUD DIRECTORY…</div>';try{const response=await fetch(`${SUPABASE_URL}/rest/v1/post_it_catalog?select=id,title,updated_at&order=updated_at.desc`,{headers});if(!response.ok)throw Error();const notes=await response.json();document.querySelector('#noteCount').textContent=`${notes.length} NOTE${notes.length===1?'':'S'} ONLINE`;renderNotes(notes);}catch{notesGrid.innerHTML='<div class="empty">RUN post-it/supabase-schema.sql TO INITIALIZE THE CLOUD NOTEBOOK.</div>';document.querySelector('#noteCount').textContent='OFFLINE';}}
function renderNotes(notes){notesGrid.replaceChildren();if(!notes.length){notesGrid.innerHTML='<div class="empty">NO NOTES YET. CREATE THE FIRST DRAFT ABOVE.</div>';return;}notes.forEach((note,index)=>{const card=document.createElement('article');card.className='note-card';card.dataset.number=String(index+1).padStart(2,'0');card.innerHTML='<h3></h3><time></time><input type="password" maxlength="128" autocomplete="current-password" placeholder="Password"><div class="note-actions"><button class="open-note" type="button">Open</button><button class="delete-note" type="button">Delete</button></div><p class="note-message" role="status"></p>';card.querySelector('h3').textContent=note.title;card.querySelector('time').textContent=`UPDATED ${dateLabel(note.updated_at)}`;const password=card.querySelector('input'),message=card.querySelector('.note-message'),open=card.querySelector('.open-note');open.onclick=()=>openNote(note,password.value,message);password.addEventListener('keydown',event=>{if(event.key==='Enter')open.click();});card.querySelector('.delete-note').onclick=()=>deleteNote(note,password.value,message);notesGrid.append(card);});}
async function openNote(note,password,message){message.textContent='';if(!password){message.textContent='PASSWORD REQUIRED';return;}try{const result=await rpc('open_post_it_note',{note_id:note.id,note_password:password}),record=result[0];if(!record){message.textContent='INCORRECT PASSWORD';return;}currentNote={id:note.id,password};editorTitle.value=record.note_title;editorContent.innerHTML=cleanHtml(record.note_content||'');updateCount();libraryView.hidden=true;editorView.hidden=false;saveStatus.textContent=`OPENED · ${dateLabel(record.note_updated_at)}`;editorContent.focus();}catch(error){message.textContent=error.message.toUpperCase();}}
async function deleteNote(note,password,message){message.textContent='';if(!password){message.textContent='PASSWORD REQUIRED';return;}if(!confirm(`Permanently delete “${note.title}”?`))return;try{const deleted=await rpc('delete_post_it_note',{note_id:note.id,note_password:password});if(!deleted){message.textContent='INCORRECT PASSWORD';return;}await loadNotes();}catch(error){message.textContent=error.message.toUpperCase();}}
function saveNote(){clearTimeout(saveTimer);if(!currentNote)return saveChain;const note={...currentNote},title=editorTitle.value.trim()||'Untitled note',content=cleanHtml(editorContent.innerHTML);saveStatus.textContent='SAVING…';saveChain=saveChain.catch(()=>{}).then(async()=>{try{const saved=await rpc('save_post_it_note',{note_id:note.id,note_password:note.password,new_title:title,new_content:content});if(currentNote?.id===note.id)saveStatus.textContent=saved?`SAVED · ${new Date().toLocaleTimeString()}`:'PASSWORD NO LONGER VALID';}catch(error){if(currentNote?.id===note.id)saveStatus.textContent=error.message.toUpperCase();}});return saveChain;}
function scheduleSave(){saveStatus.textContent='UNSAVED CHANGES';clearTimeout(saveTimer);saveTimer=setTimeout(saveNote,650);updateCount();}
function updateCount(){document.querySelector('#characterCount').textContent=`${editorContent.innerText.length.toLocaleString()} characters`;}
function closeDictionary(){dictionaryPopup.hidden=true;}
function wordAtPoint(x,y){let node,offset;if(document.caretPositionFromPoint){const position=document.caretPositionFromPoint(x,y);node=position?.offsetNode;offset=position?.offset;}else if(document.caretRangeFromPoint){const range=document.caretRangeFromPoint(x,y);node=range?.startContainer;offset=range?.startOffset;}if(node?.nodeType!==Node.TEXT_NODE)return'';const text=node.textContent||'';let start=Math.min(offset,text.length),end=start;while(start>0&&/[\p{L}\p{M}'’]/u.test(text[start-1]))start--;while(end<text.length&&/[\p{L}\p{M}'’]/u.test(text[end]))end++;return text.slice(start,end).replace(/^['’]+|['’]+$/g,'');}
function tidyDefinition(text){return text.replace(/^.*?\n(?=[^\n]{2})/,'').replace(/\n{3,}/g,'\n\n').trim().slice(0,900);}
function positionDictionary(x,y){const margin=14,width=Math.min(390,window.innerWidth-margin*2);dictionaryPopup.style.width=`${width}px`;dictionaryPopup.style.left=`${Math.max(margin,Math.min(x-width/2,window.innerWidth-width-margin))}px`;dictionaryPopup.style.top=`${Math.max(margin,Math.min(y+18,window.innerHeight-260))}px`;}
async function lookupWord(word,x,y){dictionaryPopup.hidden=false;dictionaryWord.textContent=word;dictionaryMeaning.textContent='SEARCHING THE DICTIONARY…';dictionarySource.hidden=true;positionDictionary(x,y);const greek=/[\u0370-\u03ff\u1f00-\u1fff]/u.test(word);try{let meaning='',source='';if(!greek){const response=await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(word)}`);if(response.ok){const entries=await response.json(),meanings=entries[0]?.meanings||[];meaning=meanings.slice(0,3).map(item=>{const definitions=item.definitions?.slice(0,2).map(entry=>`• ${entry.definition}`).join('\n');return definitions?`${item.partOfSpeech||'Meaning'}\n${definitions}`:'';}).filter(Boolean).join('\n\n');source=entries[0]?.sourceUrls?.[0]||`https://en.wiktionary.org/wiki/${encodeURIComponent(word)}`;}}if(!meaning){const language=greek?'el':'en',url=`https://${language}.wiktionary.org/w/api.php?action=query&prop=extracts&explaintext=1&exintro=1&redirects=1&format=json&origin=*&titles=${encodeURIComponent(word)}`,response=await fetch(url);if(response.ok){const data=await response.json(),page=Object.values(data.query?.pages||{})[0];if(page&&!page.missing)meaning=tidyDefinition(page.extract||'');source=`https://${language}.wiktionary.org/wiki/${encodeURIComponent(word)}`;}}dictionaryMeaning.textContent=meaning||'No definition was found for this word.';if(source){dictionarySource.href=source;dictionarySource.hidden=false;}}catch{dictionaryMeaning.textContent='The dictionary could not be reached. Check your connection and try again.';}}
function closeEditor(){clearTimeout(saveTimer);closeDictionary();currentNote=null;editorTitle.value='';editorTitle.readOnly=false;editorContent.innerHTML='';editorContent.contentEditable='true';editorView.classList.remove('reading-mode');const readButton=document.querySelector('#readModeButton');readButton.textContent='Read';readButton.setAttribute('aria-pressed','false');editorView.hidden=true;libraryView.hidden=false;loadNotes();window.scrollTo(0,0);}
async function toggleReadingMode(){const entering=!editorView.classList.contains('reading-mode'),button=document.querySelector('#readModeButton');if(entering)await saveNote();else closeDictionary();editorView.classList.toggle('reading-mode',entering);editorTitle.readOnly=entering;editorContent.contentEditable=String(!entering);button.textContent=entering?'Edit':'Read';button.setAttribute('aria-pressed',String(entering));if(!entering)editorContent.focus();}
document.querySelector('#newNoteForm').addEventListener('submit',async event=>{event.preventDefault();const title=document.querySelector('#newTitle'),password=document.querySelector('#newPassword'),status=document.querySelector('#newStatus'),button=event.currentTarget.querySelector('button');status.textContent='';button.disabled=true;try{const id=await rpc('create_post_it_note',{note_title:title.value.trim(),note_password:password.value,note_content:''});const note={id,title:title.value.trim()};const pass=password.value;title.value='';password.value='';await openNote(note,pass,status);}catch(error){status.textContent=error.message.toUpperCase();}finally{button.disabled=false;}});
editorTitle.addEventListener('input',scheduleSave);editorContent.addEventListener('input',scheduleSave);document.querySelector('#saveButton').onclick=saveNote;document.querySelector('#backButton').onclick=async()=>{await saveNote();closeEditor();};document.querySelector('#deleteOpenButton').onclick=async()=>{if(!currentNote||!confirm(`Permanently delete “${editorTitle.value}”?`))return;clearTimeout(saveTimer);await saveChain;const deleted=await rpc('delete_post_it_note',{note_id:currentNote.id,note_password:currentNote.password});if(deleted)closeEditor();};
editorContent.addEventListener('paste',event=>{event.preventDefault();const rich=event.clipboardData.getData('text/html'),plain=event.clipboardData.getData('text/plain');if(rich)document.execCommand('insertHTML',false,cleanHtml(rich,true));else document.execCommand('insertText',false,plain);});
document.querySelectorAll('[data-command]').forEach(button=>{button.addEventListener('mousedown',event=>event.preventDefault());button.addEventListener('click',()=>{editorContent.focus();document.execCommand(button.dataset.command,false);scheduleSave();});});
document.querySelector('#readModeButton').addEventListener('click',toggleReadingMode);
editorContent.addEventListener('click',event=>{if(!editorView.classList.contains('reading-mode'))return;const word=wordAtPoint(event.clientX,event.clientY);if(word)lookupWord(word,event.clientX,event.clientY);});
document.querySelector('#closeDictionary').addEventListener('click',closeDictionary);
document.addEventListener('keydown',event=>{if(event.key!=='Escape'||!editorView.classList.contains('reading-mode'))return;if(!dictionaryPopup.hidden)closeDictionary();else toggleReadingMode();});
loadNotes();
