const SUPABASE_URL='https://owceeowarwqjsxpylnoo.supabase.co';
const SUPABASE_KEY='sb_publishable_DxH30XOgchm8PifrXNKn-w_9fRNFoQg';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'};
const libraryView=document.querySelector('#libraryView'),editorView=document.querySelector('#editorView'),notesGrid=document.querySelector('#notesGrid');
const editorTitle=document.querySelector('#editorTitle'),editorContent=document.querySelector('#editorContent'),saveStatus=document.querySelector('#saveStatus');
let currentNote=null,saveTimer=null,saveChain=Promise.resolve();
async function rpc(name,body){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(body)});if(!response.ok)throw Error('The notes database needs the latest Post it Supabase setup.');return response.json();}
function dateLabel(value){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
async function loadNotes(){notesGrid.innerHTML='<div class="empty">READING CLOUD DIRECTORY…</div>';try{const response=await fetch(`${SUPABASE_URL}/rest/v1/post_it_catalog?select=id,title,updated_at&order=updated_at.desc`,{headers});if(!response.ok)throw Error();const notes=await response.json();document.querySelector('#noteCount').textContent=`${notes.length} NOTE${notes.length===1?'':'S'} ONLINE`;renderNotes(notes);}catch{notesGrid.innerHTML='<div class="empty">RUN post-it/supabase-schema.sql TO INITIALIZE THE CLOUD NOTEBOOK.</div>';document.querySelector('#noteCount').textContent='OFFLINE';}}
function renderNotes(notes){notesGrid.replaceChildren();if(!notes.length){notesGrid.innerHTML='<div class="empty">NO NOTES YET. CREATE THE FIRST DRAFT ABOVE.</div>';return;}notes.forEach((note,index)=>{const card=document.createElement('article');card.className='note-card';card.dataset.number=String(index+1).padStart(2,'0');card.innerHTML='<h3></h3><time></time><input type="password" maxlength="128" autocomplete="current-password" placeholder="Password"><div class="note-actions"><button class="open-note" type="button">Open</button><button class="delete-note" type="button">Delete</button></div><p class="note-message" role="status"></p>';card.querySelector('h3').textContent=note.title;card.querySelector('time').textContent=`UPDATED ${dateLabel(note.updated_at)}`;const password=card.querySelector('input'),message=card.querySelector('.note-message'),open=card.querySelector('.open-note');open.onclick=()=>openNote(note,password.value,message);password.addEventListener('keydown',event=>{if(event.key==='Enter')open.click();});card.querySelector('.delete-note').onclick=()=>deleteNote(note,password.value,message);notesGrid.append(card);});}
async function openNote(note,password,message){message.textContent='';if(!password){message.textContent='PASSWORD REQUIRED';return;}try{const result=await rpc('open_post_it_note',{note_id:note.id,note_password:password}),record=result[0];if(!record){message.textContent='INCORRECT PASSWORD';return;}currentNote={id:note.id,password};editorTitle.value=record.note_title;editorContent.value=record.note_content||'';updateCount();libraryView.hidden=true;editorView.hidden=false;saveStatus.textContent=`OPENED · ${dateLabel(record.note_updated_at)}`;editorContent.focus();}catch(error){message.textContent=error.message.toUpperCase();}}
async function deleteNote(note,password,message){message.textContent='';if(!password){message.textContent='PASSWORD REQUIRED';return;}if(!confirm(`Permanently delete “${note.title}”?`))return;try{const deleted=await rpc('delete_post_it_note',{note_id:note.id,note_password:password});if(!deleted){message.textContent='INCORRECT PASSWORD';return;}await loadNotes();}catch(error){message.textContent=error.message.toUpperCase();}}
function saveNote(){clearTimeout(saveTimer);if(!currentNote)return saveChain;const note={...currentNote},title=editorTitle.value.trim()||'Untitled note',content=editorContent.value;saveStatus.textContent='SAVING…';saveChain=saveChain.catch(()=>{}).then(async()=>{try{const saved=await rpc('save_post_it_note',{note_id:note.id,note_password:note.password,new_title:title,new_content:content});if(currentNote?.id===note.id)saveStatus.textContent=saved?`SAVED · ${new Date().toLocaleTimeString()}`:'PASSWORD NO LONGER VALID';}catch(error){if(currentNote?.id===note.id)saveStatus.textContent=error.message.toUpperCase();}});return saveChain;}
function scheduleSave(){saveStatus.textContent='UNSAVED CHANGES';clearTimeout(saveTimer);saveTimer=setTimeout(saveNote,650);updateCount();}
function updateCount(){document.querySelector('#characterCount').textContent=`${editorContent.value.length.toLocaleString()} characters`;}
function closeEditor(){clearTimeout(saveTimer);currentNote=null;editorTitle.value='';editorContent.value='';editorView.hidden=true;libraryView.hidden=false;loadNotes();window.scrollTo(0,0);}
document.querySelector('#newNoteForm').addEventListener('submit',async event=>{event.preventDefault();const title=document.querySelector('#newTitle'),password=document.querySelector('#newPassword'),status=document.querySelector('#newStatus'),button=event.currentTarget.querySelector('button');status.textContent='';button.disabled=true;try{const id=await rpc('create_post_it_note',{note_title:title.value.trim(),note_password:password.value,note_content:''});const note={id,title:title.value.trim()};const pass=password.value;title.value='';password.value='';await openNote(note,pass,status);}catch(error){status.textContent=error.message.toUpperCase();}finally{button.disabled=false;}});
editorTitle.addEventListener('input',scheduleSave);editorContent.addEventListener('input',scheduleSave);document.querySelector('#saveButton').onclick=saveNote;document.querySelector('#backButton').onclick=async()=>{await saveNote();closeEditor();};document.querySelector('#deleteOpenButton').onclick=async()=>{if(!currentNote||!confirm(`Permanently delete “${editorTitle.value}”?`))return;clearTimeout(saveTimer);await saveChain;const deleted=await rpc('delete_post_it_note',{note_id:currentNote.id,note_password:currentNote.password});if(deleted)closeEditor();};
loadNotes();
