const collections=window.FLORAL_GALLERY;
const catalogueView=document.querySelector('#catalogueView'),galleryView=document.querySelector('#galleryView'),categoryGrid=document.querySelector('#categoryGrid'),photoGrid=document.querySelector('#photoGrid'),roseFilters=document.querySelector('#roseFilters');
const lightbox=document.querySelector('#lightbox'),lightboxImage=document.querySelector('#lightboxImage'),lightboxCaption=document.querySelector('#lightboxCaption');
let activePhotos=[],activeIndex=0;

function allImages(category){return category.groups?category.groups.flatMap(group=>group.images):category.images;}
function renderCategories(){const total=collections.reduce((sum,category)=>sum+allImages(category).length,0);document.querySelector('#collectionCount').textContent=`${collections.length} families · ${total} specimens`;categoryGrid.replaceChildren();collections.forEach(category=>{const images=allImages(category),card=document.createElement('button');card.type='button';card.className=`category-card${images.length?'':' awaiting'}`;card.innerHTML=`<span class="category-number">${category.number}</span><span class="category-image"></span><span class="category-copy"><strong>${category.title}</strong><small>${images.length?`${images.length} specimen${images.length===1?'':'s'}`:'Awaiting specimens'}</small></span>`;const image=card.querySelector('.category-image');if(images.length)image.style.backgroundImage=`url("${encodeURI(images[0][0])}")`;card.addEventListener('click',()=>{location.hash=category.id;});categoryGrid.append(card);});}
function openCategory(id,groupId){const category=collections.find(item=>item.id===id);if(!category)return;catalogueView.hidden=true;galleryView.hidden=false;document.querySelector('#galleryNumber').textContent=`Collection ${category.number}`;document.querySelector('#galleryTitle').textContent=category.title;document.querySelector('#gallerySubtitle').textContent=category.subtitle;roseFilters.hidden=!category.groups;if(category.groups){roseFilters.replaceChildren();category.groups.forEach((group,index)=>{const button=document.createElement('button');button.type='button';button.textContent=`${group.title} · ${group.images.length}`;button.className=group.id===(groupId||category.groups[0].id)?'active':'';button.onclick=()=>{location.hash=`${category.id}/${group.id}`;renderPhotos(group.images);[...roseFilters.children].forEach(item=>item.classList.toggle('active',item===button));};roseFilters.append(button);});const group=category.groups.find(item=>item.id===groupId)||category.groups[0];renderPhotos(group.images);}else renderPhotos(category.images);galleryView.scrollIntoView({block:'start'});}
function renderPhotos(photos){activePhotos=photos;photoGrid.replaceChildren();if(!photos.length){photoGrid.innerHTML='<div class="empty-gallery"><span>❦</span><h2>This page awaits its first bloom.</h2><p>Add photographs to this collection when they arrive.</p></div>';return;}photos.forEach((photo,index)=>{const figure=document.createElement('figure');figure.className='photo-card';figure.innerHTML=`<button type="button"><img loading="lazy" alt=""><span>View specimen</span></button><figcaption><i>${String(index+1).padStart(2,'0')}</i><strong></strong></figcaption>`;const image=figure.querySelector('img');image.src=photo[0];image.alt=photo[1];figure.querySelector('strong').textContent=photo[1];figure.querySelector('button').onclick=()=>openLightbox(index);photoGrid.append(figure);});}
function openLightbox(index){activeIndex=index;const photo=activePhotos[index];lightboxImage.src=photo[0];lightboxImage.alt=photo[1];lightboxCaption.textContent=photo[1];if(!lightbox.open)lightbox.showModal();}
function changePhoto(direction){if(!activePhotos.length)return;openLightbox((activeIndex+direction+activePhotos.length)%activePhotos.length);}
function route(){const [category,group]=decodeURIComponent(location.hash.slice(1)).split('/');if(category)openCategory(category,group);else{galleryView.hidden=true;catalogueView.hidden=false;window.scrollTo({top:0});}}
document.querySelector('#backButton').onclick=()=>{location.hash='';};
document.querySelector('#closeLightbox').onclick=()=>lightbox.close();
document.querySelector('#previousPhoto').onclick=()=>changePhoto(-1);
document.querySelector('#nextPhoto').onclick=()=>changePhoto(1);
lightbox.addEventListener('click',event=>{if(event.target===lightbox)lightbox.close();});
document.addEventListener('keydown',event=>{if(!lightbox.open)return;if(event.key==='ArrowLeft')changePhoto(-1);if(event.key==='ArrowRight')changePhoto(1);});
window.addEventListener('hashchange',route);
renderCategories();route();
