// Add your family videos here. Use only the YouTube video ID, not the full URL.
// Example: for https://youtu.be/dQw4w9WgXcQ the ID is dQw4w9WgXcQ.
window.FAMILY_VIDEOS = [
  {
    id: "CkguSydNqEI",
    title: "A short story by Luke",
    year: "2022",
    category: "Lucas",
    tags: ["Family", "Lucas"],
    location: "unknown",
    duration: "01:17",
    featured: true,
  },
  {
    id: "WWeRgj7uwwk",
    title: "My father Athanasios talks about our family's chronicles",
    year: "2022",
    category: "Grandpa Thanasis",
    tags: ["Family", "Grandpa Thanasis"],
    location: "unknown",
    duration: "02:07:23",
  },
  {
    id: "2H7JwEF94Ms",
    title: "at Thermi's dam",
    year: "2021",
    category: "Family",
    tags: ["Family"],
    location: "Thermi's dam",
    duration: "21:03",
  },
  {
    id: "sXirS5pV9W8",
    title: "We are building lego",
    year: "2021",
    category: "Family",
    tags: ["Family"],
    location: "Kondyli 17, Komotini, Greece",
    duration: "01:17:48",
  },
  {
    id: "d4uNFgFC6Fo",
    title: "Thanos is sharing his dream",
    year: "2023",
    category: "Thanos",
    tags: ["Family", "Thanos"],
    location: "Rhodites, Komotini, Greece",
    duration: "02:13",
  },
  {
    id: "D0yNI2lG7IM",
    title: "the Vryonis are singing before bedtime",
    year: "2019",
    category: "Family",
    tags: ["Family"],
    location: "Rhodites, Komotini, Greece",
    duration: "01:43",
  },
  {
    id: "hmGC60n--10",
    title: "Lucas and the cafeteria of friendship, where all the superzings, bad and good, are reconciled",
    year: "2023",
    category: "Lucas",
    tags: ["Lucas"],
    location: "Rhodites, Komotini, Greece",
    duration: "04:36",
  },
];
