const SUPABASE_URL='https://owceeowarwqjsxpylnoo.supabase.co';
const SUPABASE_KEY='sb_publishable_DxH30XOgchm8PifrXNKn-w_9fRNFoQg';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'};
const params=new URLSearchParams(location.search),playerSession=params.get('game');
let sessionId=playerSession||'',dmKey='',role=playerSession?'player':'dm',syncTimer=null,pollTimer=null,lastRemoteUpdate='',movedHeroId='';
const campaignHome=document.querySelector('#campaignHome'),setupView=document.querySelector('#setupView'),playView=document.querySelector('#playView');
const setupCanvas=document.querySelector('#setupCanvas'),playCanvas=document.querySelector('#playCanvas');
const setupContext=setupCanvas.getContext('2d'),playContext=playCanvas.getContext('2d');
const fogCanvas=document.createElement('canvas'),fogContext=fogCanvas.getContext('2d'),colourCanvas=document.createElement('canvas'),colourContext=colourCanvas.getContext('2d');
const mapImage=new Image(),tokens=[];let mapFile=null,mapSource='',mapReady=false,selectedToken=null,draggingToken=null,dragOffset=null,panning=null,mode='home',dmFogPreview=false,fogMode='normal',reveals=[],campaignName='',fogBrushMode=null,paintingFog=false;
const colors={hero:'#e5bf49',monster:'#c74b3e','monster-xl':'#77281f',npc:'#5a9b7b'};
function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});}
function loadImage(source){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.crossOrigin='anonymous';image.src=source;});}
function setMapSource(source){return new Promise((resolve,reject)=>{mapImage.onload=()=>{mapReady=true;resizeForMap();resolve();};mapImage.onerror=reject;mapImage.crossOrigin='anonymous';mapImage.src=source;});}
function resizeForMap(){const width=Math.max(1,mapImage.naturalWidth),height=Math.max(1,mapImage.naturalHeight);for(const canvas of[setupCanvas,playCanvas,fogCanvas,colourCanvas]){canvas.width=width;canvas.height=height;}resetFog(false);}
function pointFromEvent(canvas,event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height};}
function tokenDiameter(){return Number(document.querySelector('#tokenSize').value);}
function sightPercent(){return Number(document.querySelector('#visionRadius').value);}
function tokenRadius(token){const base=tokenDiameter()/2;return token?.type==='monster-xl'?base*2:base;}
function visionRadius(){return Math.min(playCanvas.width,playCanvas.height)*(sightPercent()/100);}
function drawToken(context,token){const radius=tokenRadius(token);context.save();context.beginPath();context.arc(token.x,token.y,radius,0,Math.PI*2);context.clip();context.drawImage(token.image,token.x-radius,token.y-radius,radius*2,radius*2);context.restore();context.beginPath();context.arc(token.x,token.y,radius+1,0,Math.PI*2);context.strokeStyle=colors[token.type];context.lineWidth=Math.max(1,radius*.13);context.stroke();}
function drawSetup(){setupContext.clearRect(0,0,setupCanvas.width,setupCanvas.height);if(!mapReady)return;setupContext.drawImage(mapImage,0,0,setupCanvas.width,setupCanvas.height);tokens.filter(item=>item.placed).forEach(token=>drawToken(setupContext,token));}
function recordFogStroke(x,y,radius,action){const last=reveals.at(-1);if(!last||last.action!==action||Math.hypot(last.x-x,last.y-y)>radius*.12)reveals.push({x:Math.round(x),y:Math.round(y),radius:Math.round(radius),action});}
function paintFog(x,y,radius,action='reveal',record=false){fogContext.save();fogContext.globalCompositeOperation=action==='hide'?'source-over':'destination-out';const gradient=fogContext.createRadialGradient(x,y,radius*.7,x,y,radius);gradient.addColorStop(0,'rgba(0,0,0,1)');gradient.addColorStop(1,'rgba(0,0,0,0)');fogContext.fillStyle=gradient;fogContext.beginPath();fogContext.arc(x,y,radius,0,Math.PI*2);fogContext.fill();fogContext.restore();if(record)recordFogStroke(x,y,radius,action);}
function carve(x,y,record=false){paintFog(x,y,visionRadius(),'reveal',record);}
function revealAt(token,record=false){if(token.type!=='hero')return;carve(token.x,token.y,record);}
function resetFog(sync=true){fogMode='normal';fogContext.globalCompositeOperation='source-over';fogContext.fillStyle='#000';fogContext.fillRect(0,0,fogCanvas.width,fogCanvas.height);reveals=[];tokens.filter(token=>token.placed&&token.type==='hero').forEach(token=>revealAt(token,true));if(mode==='play')drawPlay();if(sync)scheduleSync();}
function rebuildFog(){fogContext.globalCompositeOperation='source-over';fogContext.clearRect(0,0,fogCanvas.width,fogCanvas.height);if(fogMode!=='revealed'){fogContext.fillStyle='#000';fogContext.fillRect(0,0,fogCanvas.width,fogCanvas.height);}reveals.forEach(point=>paintFog(point.x,point.y,point.radius||visionRadius(),point.action||'reveal'));}
function tokenIsRevealed(token){if(token.type==='hero')return true;const x=Math.max(0,Math.min(fogCanvas.width-1,Math.round(token.x))),y=Math.max(0,Math.min(fogCanvas.height-1,Math.round(token.y)));return fogContext.getImageData(x,y,1,1).data[3]<110;}
function drawPlay(){playContext.clearRect(0,0,playCanvas.width,playCanvas.height);if(!mapReady)return;const preview=role==='player'||dmFogPreview;if(preview){playContext.drawImage(mapImage,0,0,playCanvas.width,playCanvas.height);playContext.drawImage(fogCanvas,0,0);}else{playContext.save();playContext.filter='grayscale(1)';playContext.drawImage(mapImage,0,0,playCanvas.width,playCanvas.height);playContext.restore();colourContext.clearRect(0,0,colourCanvas.width,colourCanvas.height);colourContext.globalCompositeOperation='source-over';colourContext.drawImage(mapImage,0,0,colourCanvas.width,colourCanvas.height);colourContext.globalCompositeOperation='destination-out';colourContext.drawImage(fogCanvas,0,0);colourContext.globalCompositeOperation='source-over';playContext.drawImage(colourCanvas,0,0);}tokens.filter(item=>item.placed&&(!preview||tokenIsRevealed(item))).forEach(token=>drawToken(playContext,token));}
function hitToken(point){return [...tokens].reverse().find(token=>token.placed&&(role==='dm'||token.type==='hero')&&Math.hypot(token.x-point.x,token.y-point.y)<=Math.max(10,tokenRadius(token)*1.25));}
function renderLibrary(){const library=document.querySelector('#tokenLibrary');library.replaceChildren();if(!tokens.length){library.innerHTML='<p class="empty-library">Your tokens will appear here.</p>';return;}for(const token of tokens){const button=document.createElement('button');button.type='button';button.className=`token-entry${selectedToken===token.id?' active':''}${token.placed?' placed':''}`;button.innerHTML='<img alt=""><span></span><small></small>';button.querySelector('img').src=token.source;button.querySelector('span').textContent=token.name;button.querySelector('small').textContent=token.placed?'Placed':token.type;button.onclick=()=>{selectedToken=token.id;renderLibrary();};library.append(button);}}
function updateReady(){const ready=mapReady&&tokens.some(token=>token.type==='hero'&&token.placed);document.querySelector('#readyButton').disabled=!ready;document.querySelector('#readyMessage').textContent=ready?'Your table is ready.':'Add a map and place at least one hero.';}
function publicUrl(path){return `${SUPABASE_URL}/storage/v1/object/public/rpg-assets/${path.split('/').map(encodeURIComponent).join('/')}`;}
async function uploadAsset(file,prefix){const extension=(file.name.split('.').pop()||'png').toLowerCase().replace(/[^a-z0-9]/g,'')||'png',path=`${sessionId}/${prefix}-${crypto.randomUUID()}.${extension}`;const response=await fetch(`${SUPABASE_URL}/storage/v1/object/rpg-assets/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':file.type||'image/png'},body:file});if(!response.ok)throw Error('An image could not be uploaded. Run the RPG Supabase setup first.');return publicUrl(path);}
function serialState(){return{campaignName,mapUrl:mapSource,width:playCanvas.width,height:playCanvas.height,tokenSize:tokenDiameter(),tokenSizeUnit:'px',vision:sightPercent(),fogMode,reveals,tokens:tokens.filter(token=>token.placed).map(({id,type,name,source,cloudSource,x,y,placed})=>({id,type,name,url:cloudSource||source,x,y,placed}))};}
function savedCampaigns(){try{return JSON.parse(localStorage.getItem('rpg-saved-campaigns'))||[];}catch{return[];}}
function storeCampaigns(items){localStorage.setItem('rpg-saved-campaigns',JSON.stringify(items));}
function saveCampaign(){const items=savedCampaigns(),existing=items.find(item=>item.id===sessionId),entry={id:sessionId,key:dmKey,name:campaignName,updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,entry);else items.unshift(entry);storeCampaigns(items);}
function automaticName(){return `Adventure · ${new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date())}`;}
function renderCampaigns(items=[]){const list=document.querySelector('#campaignList');document.querySelector('#campaignCount').textContent=`${items.length} saved online`;list.replaceChildren();if(!items.length){list.innerHTML='<div class="no-campaigns">No saved campaigns yet.</div>';return;}const local=new Map(savedCampaigns().map(item=>[item.id,item]));for(const item of items){item.key=local.get(item.id)?.key||'';const card=document.createElement('article');card.className='campaign-card';card.innerHTML='<div><h3></h3><p></p></div><input class="campaign-password" type="password" maxlength="128" autocomplete="current-password"><div class="campaign-actions"><button class="continue-campaign" type="button">Open</button><button class="delete-campaign" type="button">Delete</button></div><p class="campaign-card-status" role="status"></p>';card.querySelector('h3').textContent=item.name;card.querySelector('p').textContent=`Last played ${new Date(item.updatedAt).toLocaleString()}`;const password=card.querySelector('.campaign-password'),status=card.querySelector('.campaign-card-status'),open=card.querySelector('.continue-campaign');password.placeholder=item.protected?'Campaign password':'Choose a password for this older campaign';open.textContent=item.protected?'Open':'Protect & open';async function access(){status.textContent='';if(!password.value){status.textContent='Enter the campaign password.';return null;}if(!item.protected){if(!item.key){status.textContent='Open this older campaign from its original DM link first.';return null;}const protectedResponse=await fetch(`${SUPABASE_URL}/rest/v1/rpc/set_rpg_password`,{method:'POST',headers,body:JSON.stringify({session_id:item.id,session_key:item.key,new_password:password.value})});if(!protectedResponse.ok||await protectedResponse.json()!==true){status.textContent='The password could not be added.';return null;}item.protected=true;return item.key;}const key=await unlockCampaign(item.id,password.value);if(!key)status.textContent='Incorrect password.';return key;}open.onclick=async()=>{open.disabled=true;const key=await access();open.disabled=false;if(key)continueCampaign({...item,key});};password.addEventListener('keydown',event=>{if(event.key==='Enter')open.click();});card.querySelector('.delete-campaign').onclick=async()=>{const key=await access();if(key)deleteCampaign({...item,key});};list.append(card);}}
async function campaignExists(id){try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpg_public_sessions?id=eq.${encodeURIComponent(id)}&select=id`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}}),rows=await response.json();return response.ok&&rows.length>0;}catch{return false;}}
async function refreshCampaignLibrary(){const list=document.querySelector('#campaignList');list.innerHTML='<div class="no-campaigns">Loading saved campaigns…</div>';try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpg_campaign_catalog?select=id,name,updated_at,password_protected&order=updated_at.desc`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!response.ok)throw Error();const rows=await response.json();renderCampaigns(rows.map(row=>({id:row.id,name:row.name,updatedAt:row.updated_at,protected:row.password_protected})));}catch{renderCampaigns(savedCampaigns().map(item=>({...item,protected:false})));document.querySelector('#campaignFormStatus').textContent='Run the latest Supabase setup to make campaigns available on every browser.';}}
async function unlockCampaign(id,password){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/unlock_rpg_session`,{method:'POST',headers,body:JSON.stringify({session_id:id,campaign_password:password})});if(!response.ok)return null;return await response.json();}
async function createSession(password){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/create_rpg_session`,{method:'POST',headers,body:JSON.stringify({initial_state:{campaignName},campaign_password:password})});if(!response.ok)throw Error('Online password-protected campaigns need the latest rpg/supabase-schema.sql in Supabase.');const result=await response.json(),row=Array.isArray(result)?result[0]:result;sessionId=row.id;dmKey=row.dm_key;location.hash=`dm=${sessionId}.${dmKey}`;saveCampaign();}
async function pushState(){if(role!=='dm'||!sessionId||!dmKey)return false;const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/update_rpg_session`,{method:'POST',headers,body:JSON.stringify({session_id:sessionId,session_key:dmKey,new_state:serialState()})}),updated=response.ok&&await response.json()===true;if(updated)saveCampaign();document.querySelector('#playStatus').textContent=updated?(fogBrushMode?(fogBrushMode==='reveal'?'Reveal brush · paint areas players may see':'Hide brush · paint areas players may not see'):(dmFogPreview?'Player-view preview':'DM view · live')):'This campaign no longer exists';return updated;}
async function pushPlayerMove(){if(role!=='player'||!movedHeroId)return;const hero=tokens.find(token=>token.id===movedHeroId&&token.type==='hero');if(!hero)return;const move={session_id:sessionId,hero_id:hero.id,hero_x:hero.x,hero_y:hero.y,explored:reveals},send=body=>fetch(`${SUPABASE_URL}/rest/v1/rpc/move_rpg_hero`,{method:'POST',headers,body:JSON.stringify(body)});let response=await send({...move,visibility:fogMode});if(response.status===404)response=await send(move);if(response.ok&&await response.json()===true){movedHeroId='';document.querySelector('#playStatus').textContent='Player view · live';}else document.querySelector('#playStatus').textContent='Move could not be saved · retrying';}
function scheduleSync(){if(!sessionId)return;clearTimeout(syncTimer);syncTimer=setTimeout(role==='dm'?pushState:pushPlayerMove,160);}
async function fetchSession(){if(draggingToken||paintingFog)return;const response=await fetch(`${SUPABASE_URL}/rest/v1/rpg_public_sessions?id=eq.${encodeURIComponent(sessionId)}&select=state,updated_at`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!response.ok)throw Error('This RPG session is unavailable.');const rows=await response.json();if(!rows.length)throw Error('This RPG session does not exist.');if(rows[0].updated_at===lastRemoteUpdate)return;lastRemoteUpdate=rows[0].updated_at;await applyRemoteState(rows[0].state);}
async function applyRemoteState(state){campaignName=state.campaignName||campaignName||automaticName();if(!state?.mapUrl)return;if(mapSource!==state.mapUrl){mapSource=state.mapUrl;await setMapSource(mapSource);}const savedSize=Number(state.tokenSize),pixelSize=state.tokenSizeUnit==='px'?savedSize:Math.round(Math.min(playCanvas.width,playCanvas.height)*((savedSize||7)/100)),safeSize=Math.max(8,Math.min(120,pixelSize||24));document.querySelector('#tokenSize').value=safeSize;document.querySelector('#tokenSizeValue').textContent=`${safeSize} px`;document.querySelector('#visionRadius').value=state.vision||14;document.querySelector('#playVisionRadius').value=state.vision||14;document.querySelector('#playVisionValue').textContent=`${state.vision||14}%`;const existing=new Map(tokens.map(token=>[token.id,token]));for(const item of state.tokens||[]){let token=existing.get(item.id);if(!token){try{token={...item,source:item.url,cloudSource:item.url,image:await loadImage(item.url)};tokens.push(token);}catch{continue;}}Object.assign(token,item,{source:item.url,cloudSource:item.url});}for(let index=tokens.length-1;index>=0;index--)if(!(state.tokens||[]).some(item=>item.id===tokens[index].id))tokens.splice(index,1);fogMode=state.fogMode||'normal';reveals=state.reveals||[];rebuildFog();drawPlay();}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>fetchSession().catch(()=>document.querySelector('#playStatus').textContent='Connection interrupted — retrying'),700);}
function stopFogBrush(){fogBrushMode=null;paintingFog=false;document.querySelector('#revealBrushButton').classList.remove('active');document.querySelector('#hideBrushButton').classList.remove('active');document.querySelector('#stopBrushButton').hidden=true;document.querySelector('#playCanvasWrap').classList.remove('brush-active');}
function showCampaignHome(){clearInterval(pollTimer);stopFogBrush();mode='home';campaignHome.hidden=false;setupView.hidden=true;playView.hidden=true;document.body.classList.remove('playing','player-role');history.replaceState(null,'',location.pathname);refreshCampaignLibrary();window.scrollTo(0,0);}
function clearTable(){mapReady=false;mapFile=null;mapSource='';selectedToken=null;draggingToken=null;stopFogBrush();fogMode='normal';reveals=[];tokens.length=0;setupCanvas.width=1200;setupCanvas.height=760;setupContext.clearRect(0,0,1200,760);document.querySelector('#tokenSize').value=24;document.querySelector('#tokenSizeValue').textContent='24 px';document.querySelector('#mapInput').value='';document.querySelector('#mapStatus').textContent='Waiting for a map';document.querySelector('#canvasPlaceholder').hidden=false;renderLibrary();updateReady();}
function showDmPlay(){mode='play';campaignHome.hidden=true;setupView.hidden=true;playView.hidden=false;document.body.classList.add('playing');document.body.classList.remove('player-role');document.querySelectorAll('[data-dm-only]').forEach(item=>item.hidden=false);document.querySelector('#playStatus').textContent='DM view · live';drawPlay();startPolling();window.scrollTo(0,0);}
async function continueCampaign(item){sessionId=item.id;dmKey=item.key;campaignName=item.name;role='dm';lastRemoteUpdate='';clearTable();location.hash=`dm=${sessionId}.${dmKey}`;try{await fetchSession();saveCampaign();if(mapReady)showDmPlay();else{mode='setup';campaignHome.hidden=true;playView.hidden=true;setupView.hidden=false;document.body.classList.remove('playing');renderLibrary();drawSetup();window.scrollTo(0,0);}}catch(error){storeCampaigns(savedCampaigns().filter(saved=>saved.id!==item.id));showCampaignHome();alert('That campaign could not be opened.');}}
function assetPath(url){const marker='/storage/v1/object/public/rpg-assets/';if(!url?.includes(marker))return null;return url.split(marker)[1].split('/').map(decodeURIComponent).join('/');}
async function deleteCampaign(item){if(!confirm(`Permanently delete “${item.name}”, including its uploaded map and tokens?`))return;try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpg_public_sessions?id=eq.${encodeURIComponent(item.id)}&select=state`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}}),rows=await response.json(),state=rows[0]?.state||{},paths=[assetPath(state.mapUrl),...(state.tokens||[]).map(token=>assetPath(token.url))].filter(Boolean);if(paths.length){const removed=await fetch(`${SUPABASE_URL}/storage/v1/object/rpg-assets`,{method:'DELETE',headers:{...headers,'x-rpg-key':item.key},body:JSON.stringify({prefixes:paths})});if(!removed.ok)throw Error('The campaign images could not be deleted.');}const deleted=await fetch(`${SUPABASE_URL}/rest/v1/rpc/delete_rpg_session`,{method:'POST',headers,body:JSON.stringify({session_id:item.id,session_key:item.key})});if(!deleted.ok)throw Error('The campaign could not be deleted.');storeCampaigns(savedCampaigns().filter(saved=>saved.id!==item.id));await refreshCampaignLibrary();}catch(error){alert(`${error.message} Please run the latest RPG Supabase setup script.`);}}
document.querySelector('#mapInput').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{mapFile=file;mapSource=await readFile(file);await setMapSource(mapSource);if(sessionId){mapSource=await uploadAsset(file,'map');mapFile=null;}tokens.forEach(token=>token.placed=false);drawSetup();document.querySelector('#canvasPlaceholder').hidden=true;document.querySelector('#mapStatus').textContent=file.name;renderLibrary();updateReady();scheduleSync();}catch{document.querySelector('#mapStatus').textContent='This image could not be opened';}});
document.querySelectorAll('[data-token-input]').forEach(input=>input.addEventListener('change',async event=>{for(const file of event.target.files){try{const source=await readFile(file),image=await loadImage(source),token={id:crypto.randomUUID(),type:input.dataset.tokenInput,name:file.name.replace(/\.[^.]+$/,''),source,image,file,x:0,y:0,placed:false};if(sessionId){token.cloudSource=await uploadAsset(file,token.type);token.file=null;}tokens.push(token);}catch{}}event.target.value='';renderLibrary();updateReady();}));
function fogBrushRadius(){return Math.min(playCanvas.width,playCanvas.height)*(Number(document.querySelector('#fogBrushSize').value)/100);}
function applyFogBrush(point){paintFog(point.x,point.y,fogBrushRadius(),fogBrushMode,true);drawPlay();scheduleSync();}
function pointerDown(canvas,event){if(!mapReady)return;event.preventDefault();const point=pointFromEvent(canvas,event);if(canvas===playCanvas&&role==='dm'&&mode==='play'&&fogBrushMode){paintingFog=true;applyFogBrush(point);canvas.setPointerCapture(event.pointerId);return;}const hit=hitToken(point);if(hit){draggingToken=hit;dragOffset={x:point.x-hit.x,y:point.y-hit.y};canvas.setPointerCapture(event.pointerId);return;}if(mode==='setup'&&selectedToken){const token=tokens.find(item=>item.id===selectedToken);if(token){token.x=point.x;token.y=point.y;token.placed=true;selectedToken=null;drawSetup();renderLibrary();updateReady();return;}}const wrapper=canvas.parentElement;panning={x:event.clientX,y:event.clientY,left:wrapper.scrollLeft,top:wrapper.scrollTop,wrapper};canvas.setPointerCapture(event.pointerId);}
function pointerMove(canvas,event){if(paintingFog){event.preventDefault();applyFogBrush(pointFromEvent(canvas,event));return;}if(panning){event.preventDefault();panning.wrapper.scrollLeft=panning.left-(event.clientX-panning.x);panning.wrapper.scrollTop=panning.top-(event.clientY-panning.y);return;}if(!draggingToken)return;event.preventDefault();const point=pointFromEvent(canvas,event),radius=tokenRadius(draggingToken),nextX=point.x-(dragOffset?.x||0),nextY=point.y-(dragOffset?.y||0);draggingToken.x=Math.max(radius,Math.min(canvas.width-radius,nextX));draggingToken.y=Math.max(radius,Math.min(canvas.height-radius,nextY));if(role==='player')movedHeroId=draggingToken.id;if(mode==='play'){revealAt(draggingToken,true);drawPlay();scheduleSync();}else drawSetup();}
function pointerUp(canvas,event){if(paintingFog){applyFogBrush(pointFromEvent(canvas,event));paintingFog=false;}else if(draggingToken)pointerMove(canvas,event);draggingToken=null;dragOffset=null;panning=null;try{canvas.releasePointerCapture(event.pointerId);}catch{}updateReady();scheduleSync();}
for(const canvas of[setupCanvas,playCanvas]){canvas.addEventListener('pointerdown',event=>pointerDown(canvas,event));canvas.addEventListener('pointermove',event=>pointerMove(canvas,event));canvas.addEventListener('pointerup',event=>pointerUp(canvas,event));canvas.addEventListener('pointercancel',()=>{draggingToken=null;dragOffset=null;panning=null;paintingFog=false;});}
function setVision(value){document.querySelector('#visionRadius').value=value;document.querySelector('#visionValue').textContent=`${value}%`;document.querySelector('#playVisionRadius').value=value;document.querySelector('#playVisionValue').textContent=`${value}%`;rebuildFog();drawPlay();scheduleSync();}
document.querySelector('#visionRadius').addEventListener('input',event=>setVision(event.target.value));document.querySelector('#playVisionRadius').addEventListener('input',event=>setVision(event.target.value));document.querySelector('#tokenSize').addEventListener('input',event=>{document.querySelector('#tokenSizeValue').textContent=`${event.target.value} px`;mode==='play'?drawPlay():drawSetup();scheduleSync();});
document.querySelector('#readyButton').addEventListener('click',async()=>{if(!mapReady||!tokens.some(token=>token.type==='hero'&&token.placed))return;const button=document.querySelector('#readyButton');button.disabled=true;button.firstChild.textContent='Preparing the table… ';try{if(!sessionId)throw Error('Return to Campaigns and create a named, password-protected adventure first.');if(mapFile)mapSource=await uploadAsset(mapFile,'map');for(const token of tokens.filter(item=>item.placed))if(token.file&&!token.cloudSource)token.cloudSource=await uploadAsset(token.file,token.type);resetFog(false);await pushState();lastRemoteUpdate='';button.firstChild.textContent='I am ready ';showDmPlay();}catch(error){document.querySelector('#readyMessage').textContent=error.message;button.disabled=false;button.firstChild.textContent='I am ready ';}});
document.querySelector('#fogPreviewButton').addEventListener('click',event=>{dmFogPreview=!dmFogPreview;event.currentTarget.textContent=dmFogPreview?'Return to DM view':'Preview player view';drawPlay();document.querySelector('#playStatus').textContent=dmFogPreview?'Player-view preview':'DM view · live';});document.querySelector('#resetFogButton').addEventListener('click',()=>resetFog());document.querySelector('#returnButton').addEventListener('click',()=>{mode='setup';campaignHome.hidden=true;playView.hidden=true;setupView.hidden=false;document.body.classList.remove('playing');renderLibrary();drawSetup();window.scrollTo(0,0);});
function setFogBrush(action){fogBrushMode=action;document.querySelector('#revealBrushButton').classList.toggle('active',action==='reveal');document.querySelector('#hideBrushButton').classList.toggle('active',action==='hide');document.querySelector('#stopBrushButton').hidden=false;document.querySelector('#playCanvasWrap').classList.add('brush-active');document.querySelector('#playStatus').textContent=action==='reveal'?'Reveal brush · paint areas players may see':'Hide brush · paint areas players may not see';}
document.querySelector('#revealBrushButton').addEventListener('click',()=>setFogBrush('reveal'));
document.querySelector('#hideBrushButton').addEventListener('click',()=>setFogBrush('hide'));
document.querySelector('#stopBrushButton').addEventListener('click',()=>{stopFogBrush();document.querySelector('#playStatus').textContent='DM view · live';});
document.querySelector('#fogBrushSize').addEventListener('input',event=>{document.querySelector('#fogBrushValue').textContent=`${event.target.value}%`;});
document.querySelector('#fullscreenButton').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.querySelector('#playCanvasWrap').requestFullscreen();else await document.exitFullscreen();}catch{}});
document.querySelector('#shareButton').addEventListener('click',async()=>{if(!await campaignExists(sessionId)){storeCampaigns(savedCampaigns().filter(saved=>saved.id!==sessionId));alert('This campaign was deleted. Return to Campaigns and create a new adventure before sharing.');showCampaignHome();return;}document.querySelector('#playerLink').value=`${location.origin}${location.pathname}?game=${sessionId}`;document.querySelector('#shareDialog').showModal();});document.querySelector('#closeShareButton').onclick=()=>document.querySelector('#shareDialog').close();document.querySelector('#copyLinkButton').onclick=async()=>{try{await navigator.clipboard.writeText(document.querySelector('#playerLink').value);document.querySelector('#copyStatus').textContent='Player link copied.';}catch{document.querySelector('#playerLink').select();document.querySelector('#copyStatus').textContent='Select and copy the link above.';}};
document.querySelector('#resetTableButton').addEventListener('click',()=>{if(!mapReady&&!tokens.length)return;if(!confirm('Clear the map and every token from this table?'))return;clearTable();scheduleSync();});
document.querySelector('#newCampaignButton').addEventListener('click',async()=>{const name=document.querySelector('#campaignName'),password=document.querySelector('#campaignPassword'),status=document.querySelector('#campaignFormStatus'),button=document.querySelector('#newCampaignButton');campaignName=name.value.trim();status.textContent='';if(!campaignName){status.textContent='Choose a name for the adventure.';name.focus();return;}if(!password.value){status.textContent='Choose a password for the campaign.';password.focus();return;}button.disabled=true;try{sessionId='';dmKey='';lastRemoteUpdate='';clearTable();await createSession(password.value);name.value='';password.value='';mode='setup';campaignHome.hidden=true;playView.hidden=true;setupView.hidden=false;window.scrollTo(0,0);}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
for(const input of[document.querySelector('#campaignName'),document.querySelector('#campaignPassword')])input.addEventListener('keydown',event=>{if(event.key==='Enter')document.querySelector('#newCampaignButton').click();});
document.querySelector('#campaignsButton').addEventListener('click',showCampaignHome);document.querySelector('#setupCampaignsButton').addEventListener('click',showCampaignHome);
async function init(){const hash=location.hash.match(/^#dm=([^.]+)\.(.+)$/);if(role==='player'){campaignHome.hidden=true;setupView.hidden=true;playView.hidden=false;mode='play';document.body.classList.add('playing','player-role');document.querySelectorAll('[data-dm-only]').forEach(item=>item.hidden=true);document.querySelector('#playStatus').textContent='Connecting to the table…';try{await fetchSession();document.querySelector('#playStatus').textContent='Player view · live';startPolling();}catch(error){document.querySelector('#playStatus').textContent=error.message;}return;}if(hash){sessionId=hash[1];dmKey=hash[2];const saved=savedCampaigns().find(item=>item.id===sessionId)||{id:sessionId,key:dmKey,name:automaticName()};await continueCampaign(saved);return;}await refreshCampaignLibrary();}
init();document.documentElement.dataset.rpgReady='true';
