create table if not exists public.memory_scores (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 20),
  score integer not null check (score >= 0),
  age integer not null check (age between 1 and 120),
  age_group text not null,
  level integer not null check (level >= 1),
  created_at timestamptz not null default now()
);
alter table public.memory_scores add column if not exists nickname text;
update public.memory_scores set nickname = 'Player' where nickname is null or btrim(nickname) = '';
alter table public.memory_scores alter column nickname set default 'Player';
alter table public.memory_scores alter column nickname set not null;
alter table public.memory_scores drop constraint if exists memory_scores_nickname_check;
alter table public.memory_scores add constraint memory_scores_nickname_check check (char_length(btrim(nickname)) between 1 and 20);
alter table public.memory_scores enable row level security;
revoke all on table public.memory_scores from anon, authenticated;
grant select, insert on table public.memory_scores to anon, authenticated;
drop policy if exists "Anyone can read scores" on public.memory_scores;
drop policy if exists "Anyone can submit a valid score" on public.memory_scores;
create policy "Anyone can read scores" on public.memory_scores for select to anon, authenticated using (true);
create policy "Anyone can submit a valid score" on public.memory_scores for insert to anon, authenticated with check (char_length(btrim(nickname)) between 1 and 20 and score >= 0 and age between 1 and 120 and level >= 1);
