import { generate, calculateScore } from './sudoku.js';
const SUPABASE_URL = 'https://owceeowarwqjsxpylnoo.supabase.co';
const SUPABASE_KEY = 'sb_publishable_DxH30XOgchm8PifrXNKn-w_9fRNFoQg';
const SCORE_ENDPOINT = `${SUPABASE_URL}/rest/v1/sudoku_scores`;
const nativeFetch = window.fetch.bind(window), STORAGE_KEY = 'gridline-browser-games';
function loadGames(){try{return JSON.parse(sessionStorage.getItem(STORAGE_KEY))||{};}catch{return {};}}
function saveGames(games){sessionStorage.setItem(STORAGE_KEY,JSON.stringify(games));}
function response(status,data){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});}
function publicGame(g){return{gameId:g.id,difficulty:g.difficulty,puzzle:g.puzzle,elapsed:Math.floor(((g.finishedAt||Date.now())-g.startedAt)/1000),status:g.status,score:g.score,submitted:Boolean(g.name),...(g.status==='solution_revealed'?{values:g.solution}:{})};}
async function onlineScores(){const r=await nativeFetch(`${SCORE_ENDPOINT}?select=nickname,score,solve_time,difficulty,created_at&order=score.desc&limit=100`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!r.ok)throw Error('The online leaderboard is not ready yet.');return(await r.json()).map(x=>({name:x.nickname,score:x.score,time:x.solve_time,difficulty:x.difficulty,date:x.created_at}));}
async function submitOnlineScore(g,nickname){const r=await nativeFetch(SCORE_ENDPOINT,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({nickname,score:g.score,solve_time:Math.floor((g.finishedAt-g.startedAt)/1000),difficulty:g.difficulty})});if(!r.ok)throw Error('The score could not be saved. Please try again.');}
window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:input.url;if(!url.startsWith('/api/'))return nativeFetch(input,init);try{const path=url.slice(5),body=init.body?JSON.parse(init.body):{};if(path==='scores'&&(!init.method||init.method==='GET'))return response(200,await onlineScores());const games=loadGames();if(path==='games'&&init.method==='POST'){if(!['Easy','Medium','Hard'].includes(body.difficulty))throw Error('Invalid difficulty');await new Promise(r=>setTimeout(r,20));const made=generate(body.difficulty),id=crypto.randomUUID(),g={...made,id,difficulty:body.difficulty,startedAt:Date.now(),status:'playing'};games[id]=g;saveGames(games);return response(200,publicGame(g));}const match=path.match(/^games\/([^/]+)(?:\/(check|reveal|score|print))?$/),g=match&&games[match[1]];if(!g)return response(404,{error:'Game not found'});if((!init.method||init.method==='GET')&&!match[2])return response(200,publicGame(g));if(match[2]==='check'){if(g.status!=='playing')throw Error('This game has already ended');const v=body.values;if(!Array.isArray(v)||v.length!==81)throw Error('Invalid board');const errors=v.flatMap((n,i)=>n&&n!==g.solution[i]?[i]:[]),complete=v.every(Boolean);if(complete&&!errors.length){g.status='solved';g.finishedAt=Date.now();g.score=calculateScore(Math.floor((g.finishedAt-g.startedAt)/1000),g.difficulty);}saveGames(games);return response(200,{...publicGame(g),errors,complete});}if(match[2]==='reveal'){if(g.status!=='playing')throw Error('This game has already ended');g.status='solution_revealed';g.finishedAt=Date.now();saveGames(games);return response(200,publicGame(g));}if(match[2]==='print'){g.finishedAt||=Date.now();g.status='printed';delete g.score;delete g.name;saveGames(games);return response(200,{...publicGame(g),printValues:body.kind==='solution'?g.solution:g.puzzle});}if(match[2]==='score'){const nickname=typeof body.name==='string'?body.name.trim():'';if(g.status!=='solved'||g.name)throw Error('This game is not eligible for submission');if(!nickname||nickname.length>20)throw Error('Enter a nickname of 1–20 characters');await submitOnlineScore(g,nickname);g.name=nickname;saveGames(games);return response(200,publicGame(g));}throw Error('Unknown action');}catch(error){return response(400,{error:error.message});}};
await import('./app.js?v=7');