create table if not exists public.sudoku_scores (
 id bigint generated by default as identity primary key,
 nickname varchar(20) not null check (char_length(trim(nickname)) between 1 and 20),
 score integer not null check (score >= 0),
 solve_time integer not null check (solve_time >= 0),
 difficulty text not null check (difficulty in ('Easy','Medium','Hard')),
 created_at timestamptz not null default now()
);
alter table public.sudoku_scores enable row level security;
revoke all on table public.sudoku_scores from anon, authenticated;
grant select, insert on table public.sudoku_scores to anon, authenticated;
drop policy if exists "Anyone can read Sudoku scores" on public.sudoku_scores;
drop policy if exists "Anyone can submit a valid Sudoku score" on public.sudoku_scores;
create policy "Anyone can read Sudoku scores" on public.sudoku_scores for select to anon, authenticated using (true);
create policy "Anyone can submit a valid Sudoku score" on public.sudoku_scores for insert to anon, authenticated with check (char_length(trim(nickname)) between 1 and 20 and score >= 0 and solve_time >= 0 and difficulty in ('Easy','Medium','Hard'));